/* Generated by :claw at 2026-02-08T23:25:56.956420Z */

#if defined(__cplusplus)
#include <new>
#endif



#include "gdextension_interface.gen.h"
#include "libgodot.h"

#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif



#if defined(__cplusplus)
}
#endif
