;; Generated by :claw at 2026-02-08T23:25:56.962719Z
(asdf:defsystem #:pz-godot-bindings
  :description "Bindings generated by pz-godot"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :claw-utils)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature (:and :x86-64 :linux))))
#-(:or (:and :x86-64 :linux))
(warn "Current platform unrecognized or unsupported by pz-godot-bindings system")