(common-lisp:defpackage :%gdext
  (:use)
  (:import-from #:%gdext.util #:defifun #:defcfunproto)
  (:export #:variant-type
           #:variant-operator
           #:variant-ptr
           #:const-variant-ptr
           #:uninitialized-variant-ptr
           #:string-name-ptr
           #:const-string-name-ptr
           #:uninitialized-string-name-ptr
           #:string-ptr
           #:const-string-ptr
           #:uninitialized-string-ptr
           #:object-ptr
           #:const-object-ptr
           #:uninitialized-object-ptr
           #:type-ptr
           #:const-type-ptr
           #:uninitialized-type-ptr
           #:method-bind-ptr
           #:int
           #:bool
           #:instance-id
           #:ref-ptr
           #:const-ref-ptr
           #:call-error-type
           #:call-error
           #:error
           #:argument
           #:expected
           #:variant-from-type-constructor-func
           #:type-from-variant-constructor-func
           #:variant-get-internal-ptr-func
           #:ptr-operator-evaluator
           #:ptr-built-in-method
           #:ptr-constructor
           #:ptr-destructor
           #:ptr-setter
           #:ptr-getter
           #:ptr-indexed-setter
           #:ptr-indexed-getter
           #:ptr-keyed-setter
           #:ptr-keyed-getter
           #:ptr-keyed-checker
           #:ptr-utility-function
           #:class-constructor
           #:instance-binding-create-callback
           #:instance-binding-free-callback
           #:instance-binding-reference-callback
           #:instance-binding-callbacks
           #:create-callback
           #:free-callback
           #:reference-callback
           #:class-instance-ptr
           #:class-set
           #:class-get
           #:class-get-rid
           #:property-info
           #:type
           #:name
           #:class-name
           #:hint
           #:hint-string
           #:usage
           #:method-info
           #:name
           #:return-value
           #:flags
           #:id
           #:argument-count
           #:arguments
           #:default-argument-count
           #:default-arguments
           #:class-get-property-list
           #:class-free-property-list
           #:class-free-property-list-2
           #:class-property-can-revert
           #:class-property-get-revert
           #:class-validate-property
           #:class-notification
           #:class-notification-2
           #:class-to-string
           #:class-reference
           #:class-unreference
           #:class-call-virtual
           #:class-create-instance
           #:class-create-instance-2
           #:class-free-instance
           #:class-recreate-instance
           #:class-get-virtual
           #:class-get-virtual-2
           #:class-get-virtual-call-data
           #:class-get-virtual-call-data-2
           #:class-call-virtual-with-data
           #:class-creation-info
           #:is-virtual
           #:is-abstract
           #:set-func
           #:get-func
           #:get-property-list-func
           #:free-property-list-func
           #:property-can-revert-func
           #:property-get-revert-func
           #:notification-func
           #:to-string-func
           #:reference-func
           #:unreference-func
           #:create-instance-func
           #:free-instance-func
           #:get-virtual-func
           #:get-rid-func
           #:class-userdata
           #:class-creation-info-2
           #:is-virtual
           #:is-abstract
           #:is-exposed
           #:set-func
           #:get-func
           #:get-property-list-func
           #:free-property-list-func
           #:property-can-revert-func
           #:property-get-revert-func
           #:validate-property-func
           #:notification-func
           #:to-string-func
           #:reference-func
           #:unreference-func
           #:create-instance-func
           #:free-instance-func
           #:recreate-instance-func
           #:get-virtual-func
           #:get-virtual-call-data-func
           #:call-virtual-with-data-func
           #:get-rid-func
           #:class-userdata
           #:class-creation-info-3
           #:is-virtual
           #:is-abstract
           #:is-exposed
           #:is-runtime
           #:set-func
           #:get-func
           #:get-property-list-func
           #:free-property-list-func
           #:property-can-revert-func
           #:property-get-revert-func
           #:validate-property-func
           #:notification-func
           #:to-string-func
           #:reference-func
           #:unreference-func
           #:create-instance-func
           #:free-instance-func
           #:recreate-instance-func
           #:get-virtual-func
           #:get-virtual-call-data-func
           #:call-virtual-with-data-func
           #:get-rid-func
           #:class-userdata
           #:class-creation-info-4
           #:is-virtual
           #:is-abstract
           #:is-exposed
           #:is-runtime
           #:icon-path
           #:set-func
           #:get-func
           #:get-property-list-func
           #:free-property-list-func
           #:property-can-revert-func
           #:property-get-revert-func
           #:validate-property-func
           #:notification-func
           #:to-string-func
           #:reference-func
           #:unreference-func
           #:create-instance-func
           #:free-instance-func
           #:recreate-instance-func
           #:get-virtual-func
           #:get-virtual-call-data-func
           #:call-virtual-with-data-func
           #:class-userdata
           #:class-creation-info-5
           #:class-library-ptr
           #:editor-get-classes-used-callback
           #:class-method-flags
           #:class-method-argument-metadata
           #:class-method-call
           #:class-method-validated-call
           #:class-method-ptr-call
           #:class-method-info
           #:name
           #:method-userdata
           #:call-func
           #:ptrcall-func
           #:method-flags
           #:has-return-value
           #:return-value-info
           #:return-value-metadata
           #:argument-count
           #:arguments-info
           #:arguments-metadata
           #:default-argument-count
           #:default-arguments
           #:class-virtual-method-info
           #:name
           #:method-flags
           #:return-value
           #:return-value-metadata
           #:argument-count
           #:arguments
           #:arguments-metadata
           #:callable-custom-call
           #:callable-custom-is-valid
           #:callable-custom-free
           #:callable-custom-hash
           #:callable-custom-equal
           #:callable-custom-less-than
           #:callable-custom-to-string
           #:callable-custom-get-argument-count
           #:callable-custom-info
           #:callable-userdata
           #:token
           #:object-id
           #:call-func
           #:is-valid-func
           #:free-func
           #:hash-func
           #:equal-func
           #:less-than-func
           #:to-string-func
           #:callable-custom-info-2
           #:callable-userdata
           #:token
           #:object-id
           #:call-func
           #:is-valid-func
           #:free-func
           #:hash-func
           #:equal-func
           #:less-than-func
           #:to-string-func
           #:get-argument-count-func
           #:script-instance-data-ptr
           #:script-instance-set
           #:script-instance-get
           #:script-instance-get-property-list
           #:script-instance-free-property-list
           #:script-instance-free-property-list-2
           #:script-instance-get-class-category
           #:script-instance-get-property-type
           #:script-instance-validate-property
           #:script-instance-property-can-revert
           #:script-instance-property-get-revert
           #:script-instance-get-owner
           #:script-instance-property-state-add
           #:script-instance-get-property-state
           #:script-instance-get-method-list
           #:script-instance-free-method-list
           #:script-instance-free-method-list-2
           #:script-instance-has-method
           #:script-instance-get-method-argument-count
           #:script-instance-call
           #:script-instance-notification
           #:script-instance-notification-2
           #:script-instance-to-string
           #:script-instance-ref-count-incremented
           #:script-instance-ref-count-decremented
           #:script-instance-get-script
           #:script-instance-is-placeholder
           #:script-language-ptr
           #:script-instance-get-language
           #:script-instance-free
           #:script-instance-ptr
           #:script-instance-info
           #:set-func
           #:get-func
           #:get-property-list-func
           #:free-property-list-func
           #:property-can-revert-func
           #:property-get-revert-func
           #:get-owner-func
           #:get-property-state-func
           #:get-method-list-func
           #:free-method-list-func
           #:get-property-type-func
           #:has-method-func
           #:call-func
           #:notification-func
           #:to-string-func
           #:refcount-incremented-func
           #:refcount-decremented-func
           #:get-script-func
           #:is-placeholder-func
           #:set-fallback-func
           #:get-fallback-func
           #:get-language-func
           #:free-func
           #:script-instance-info-2
           #:set-func
           #:get-func
           #:get-property-list-func
           #:free-property-list-func
           #:get-class-category-func
           #:property-can-revert-func
           #:property-get-revert-func
           #:get-owner-func
           #:get-property-state-func
           #:get-method-list-func
           #:free-method-list-func
           #:get-property-type-func
           #:validate-property-func
           #:has-method-func
           #:call-func
           #:notification-func
           #:to-string-func
           #:refcount-incremented-func
           #:refcount-decremented-func
           #:get-script-func
           #:is-placeholder-func
           #:set-fallback-func
           #:get-fallback-func
           #:get-language-func
           #:free-func
           #:script-instance-info-3
           #:set-func
           #:get-func
           #:get-property-list-func
           #:free-property-list-func
           #:get-class-category-func
           #:property-can-revert-func
           #:property-get-revert-func
           #:get-owner-func
           #:get-property-state-func
           #:get-method-list-func
           #:free-method-list-func
           #:get-property-type-func
           #:validate-property-func
           #:has-method-func
           #:get-method-argument-count-func
           #:call-func
           #:notification-func
           #:to-string-func
           #:refcount-incremented-func
           #:refcount-decremented-func
           #:get-script-func
           #:is-placeholder-func
           #:set-fallback-func
           #:get-fallback-func
           #:get-language-func
           #:free-func
           #:worker-thread-pool-group-task
           #:worker-thread-pool-task
           #:initialization-level
           #:initialize-callback
           #:deinitialize-callback
           #:initialization
           #:minimum-initialization-level
           #:userdata
           #:initialize
           #:deinitialize
           #:interface-function-ptr
           #:interface-get-proc-address
           #:initialization-function
           #:godot-version
           #:major
           #:minor
           #:patch
           #:string
           #:godot-version-2
           #:major
           #:minor
           #:patch
           #:hex
           #:status
           #:build
           #:hash
           #:timestamp
           #:string
           #:main-loop-startup-callback
           #:main-loop-shutdown-callback
           #:main-loop-frame-callback
           #:main-loop-callbacks
           #:startup-func
           #:shutdown-func
           #:frame-func
           #:get-godot-version
           #:get-godot-version2
           #:mem-alloc
           #:mem-realloc
           #:mem-free
           #:mem-alloc2
           #:mem-realloc2
           #:mem-free2
           #:print-error
           #:print-error-with-message
           #:print-warning
           #:print-warning-with-message
           #:print-script-error
           #:print-script-error-with-message
           #:get-native-struct-size
           #:variant-new-copy
           #:variant-new-nil
           #:variant-destroy
           #:variant-call
           #:variant-call-static
           #:variant-evaluate
           #:variant-set
           #:variant-set-named
           #:variant-set-keyed
           #:variant-set-indexed
           #:variant-get
           #:variant-get-named
           #:variant-get-keyed
           #:variant-get-indexed
           #:variant-iter-init
           #:variant-iter-next
           #:variant-iter-get
           #:variant-hash
           #:variant-recursive-hash
           #:variant-hash-compare
           #:variant-booleanize
           #:variant-duplicate
           #:variant-stringify
           #:variant-get-type
           #:variant-has-method
           #:variant-has-member
           #:variant-has-key
           #:variant-get-object-instance-id
           #:variant-get-type-name
           #:variant-can-convert
           #:variant-can-convert-strict
           #:get-variant-from-type-constructor
           #:get-variant-to-type-constructor
           #:variant-get-ptr-internal-getter
           #:variant-get-ptr-operator-evaluator
           #:variant-get-ptr-builtin-method
           #:variant-get-ptr-constructor
           #:variant-get-ptr-destructor
           #:variant-construct
           #:variant-get-ptr-setter
           #:variant-get-ptr-getter
           #:variant-get-ptr-indexed-setter
           #:variant-get-ptr-indexed-getter
           #:variant-get-ptr-keyed-setter
           #:variant-get-ptr-keyed-getter
           #:variant-get-ptr-keyed-checker
           #:variant-get-constant-value
           #:variant-get-ptr-utility-function
           #:string-new-with-latin1-chars
           #:string-new-with-utf8-chars
           #:string-new-with-utf16-chars
           #:string-new-with-utf32-chars
           #:string-new-with-wide-chars
           #:string-new-with-latin1-chars-and-len
           #:string-new-with-utf8-chars-and-len
           #:string-new-with-utf8-chars-and-len2
           #:string-new-with-utf16-chars-and-len
           #:string-new-with-utf16-chars-and-len2
           #:string-new-with-utf32-chars-and-len
           #:string-new-with-wide-chars-and-len
           #:string-to-latin1-chars
           #:string-to-utf8-chars
           #:string-to-utf16-chars
           #:string-to-utf32-chars
           #:string-to-wide-chars
           #:string-operator-index
           #:string-operator-index-const
           #:string-operator-plus-eq-string
           #:string-operator-plus-eq-char
           #:string-operator-plus-eq-cstr
           #:string-operator-plus-eq-wcstr
           #:string-operator-plus-eq-c32str
           #:string-resize
           #:string-name-new-with-latin1-chars
           #:string-name-new-with-utf8-chars
           #:string-name-new-with-utf8-chars-and-len
           #:xml-parser-open-buffer
           #:file-access-store-buffer
           #:file-access-get-buffer
           #:image-ptrw
           #:image-ptr
           #:worker-thread-pool-add-native-group-task
           #:worker-thread-pool-add-native-task
           #:packed-byte-array-operator-index
           #:packed-byte-array-operator-index-const
           #:packed-float32-array-operator-index
           #:packed-float32-array-operator-index-const
           #:packed-float64-array-operator-index
           #:packed-float64-array-operator-index-const
           #:packed-int32-array-operator-index
           #:packed-int32-array-operator-index-const
           #:packed-int64-array-operator-index
           #:packed-int64-array-operator-index-const
           #:packed-string-array-operator-index
           #:packed-string-array-operator-index-const
           #:packed-vector2-array-operator-index
           #:packed-vector2-array-operator-index-const
           #:packed-vector3-array-operator-index
           #:packed-vector3-array-operator-index-const
           #:packed-vector4-array-operator-index
           #:packed-vector4-array-operator-index-const
           #:packed-color-array-operator-index
           #:packed-color-array-operator-index-const
           #:array-operator-index
           #:array-operator-index-const
           #:array-ref
           #:array-set-typed
           #:dictionary-operator-index
           #:dictionary-operator-index-const
           #:dictionary-set-typed
           #:object-method-bind-call
           #:object-method-bind-ptrcall
           #:object-destroy
           #:global-get-singleton
           #:object-get-instance-binding
           #:object-set-instance-binding
           #:object-free-instance-binding
           #:object-set-instance
           #:object-get-class-name
           #:object-cast-to
           #:object-get-instance-from-id
           #:object-get-instance-id
           #:object-has-script-method
           #:object-call-script-method
           #:ref-get-object
           #:ref-set-object
           #:script-instance-create
           #:script-instance-create2
           #:script-instance-create3
           #:placeholder-script-instance-create
           #:placeholder-script-instance-update
           #:object-get-script-instance
           #:object-set-script-instance
           #:callable-custom-create
           #:callable-custom-create2
           #:callable-custom-get-userdata
           #:classdb-construct-object
           #:classdb-construct-object2
           #:classdb-get-method-bind
           #:classdb-get-class-tag
           #:classdb-register-extension-class
           #:classdb-register-extension-class2
           #:classdb-register-extension-class3
           #:classdb-register-extension-class4
           #:classdb-register-extension-class5
           #:classdb-register-extension-class-method
           #:classdb-register-extension-class-virtual-method
           #:classdb-register-extension-class-integer-constant
           #:classdb-register-extension-class-property
           #:classdb-register-extension-class-property-indexed
           #:classdb-register-extension-class-property-group
           #:classdb-register-extension-class-property-subgroup
           #:classdb-register-extension-class-signal
           #:classdb-unregister-extension-class
           #:get-library-path
           #:editor-add-plugin
           #:editor-remove-plugin
           #:editor-help-load-xml-from-utf8-chars
           #:editor-help-load-xml-from-utf8-chars-and-len
           #:editor-register-get-classes-used-callback
           #:register-main-loop-callbacks))